# -*- coding: utf-8 -*-
"""AlcoholSpeechDetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PhA-2jJf69vmASlopWbu-VLXksoa1XDF
"""

import os
import numpy as np
import soundfile as sf

# Create folders
os.makedirs('/content/data/sober', exist_ok=True)
os.makedirs('/content/data/intoxicated', exist_ok=True)

# Parameters for dummy audio files
duration = 2  # seconds
samplerate = 22050  # Hz

def create_sine_wave(freq, duration, samplerate):
    t = np.linspace(0, duration, int(samplerate * duration), False)
    tone = 0.5 * np.sin(2 * np.pi * freq * t)
    return tone

# Generate dummy sober audio files (e.g. lower frequency tones)
for i in range(3):
    audio = create_sine_wave(freq=440 + i*50, duration=duration, samplerate=samplerate)
    filepath = f'/content/data/sober/sober_{i+1}.wav'
    sf.write(filepath, audio, samplerate)

# Generate dummy intoxicated audio files (e.g. higher frequency tones)
for i in range(3):
    audio = create_sine_wave(freq=880 + i*50, duration=duration, samplerate=samplerate)
    filepath = f'/content/data/intoxicated/intoxicated_{i+1}.wav'
    sf.write(filepath, audio, samplerate)

# Check files
print("Sober files:", os.listdir('/content/data/sober'))
print("Intoxicated files:", os.listdir('/content/data/intoxicated'))