# -*- coding: utf-8 -*-
"""COST_LIVING_DATA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bQVxZZeT-0l_plc1ANYI9ReVS04C25Wr
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Create the dataset directly
data = {
    "Country": ["USA", "India", "Germany", "Brazil", "Australia", "UK", "Canada", "Japan", "South Africa", "UAE"],
    "AvgSalaryUSD": [5400, 800, 4200, 1500, 4800, 4000, 4100, 3800, 1200, 3900],
    "CostOfLivingIndex": [70.0, 25.0, 65.0, 40.0, 68.0, 62.0, 64.0, 60.0, 35.0, 66.0],
    "RentIndex": [55.0, 15.0, 50.0, 25.0, 52.0, 45.0, 46.0, 42.0, 22.0, 48.0],
    "FoodCostIndex": [60.0, 20.0, 55.0, 30.0, 58.0, 53.0, 54.0, 50.0, 28.0, 56.0]
}

df = pd.DataFrame(data)

# Affordability Index
df["AffordabilityIndex"] = df["AvgSalaryUSD"] / df["CostOfLivingIndex"]

# Plot salary vs cost of living
plt.figure(figsize=(12, 6))
df_sorted = df.sort_values("AvgSalaryUSD", ascending=False)
sns.barplot(x="Country", y="AvgSalaryUSD", data=df_sorted, label="Avg Salary", color='blue')
sns.barplot(x="Country", y="CostOfLivingIndex", data=df_sorted, label="Cost Index", color='orange')
plt.title("Average Salary vs Cost of Living Index")
plt.ylabel("Value")
plt.xticks(rotation=45)
plt.legend()
plt.tight_layout()
plt.show()

# Correlation heatmap
plt.figure(figsize=(8, 6))
sns.heatmap(df.corr(numeric_only=True), annot=True, cmap="coolwarm")
plt.title("Feature Correlation")
plt.show()